---
###############################
## Get Application ID       ###
###############################
    - name: Get App ID from Ravello
      ravello_get_id:
        resource_name: "{{ ravello_app_name }}"
        resource_type: applications
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      register: app
      run_once: true

###############################
##  Delete the application   ##
###############################

    - name: Delete Application on Ravello
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ app.json.id }}"
        method: DELETE
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        status_code: 204
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
      run_once: true
      changed_when: true
